#+title: Information theory
#+subtitle: Some random thoughts

* Introduction
Information is  colloquially refers  to facts.  For example,
the  health  ministry  provided  information  regarding  the
transmission of the SARS-CoV2  virus. In information theory,
information to indicate the  amount of surprise a particular
phenomenon has  about another. The amount  of information in
reading an email, it not  tied to the information content in
terms of facts. Rather, the amount of information is tied to
the amount  of surprise  the email  generates. Informational
content in the colloquial sense, can therefore be understood
as the lack of surprise in information theoretical terms. In
this post I will provide  some insights I have gathered over
the past years in working with information theory.


* Why is surprise important?
One  of  the   primary  goals  of  science   is  to  provide
understanding  for naturally  occurring phenomenon.  Human's
natural curiosity lead  it to want to  understand how birds
generate  lift  by the  flapping  of  their wings,  how  the
chameleon  blends   it  color  with  its   surrounding,  how
seemingly simple things generate complex emergent observable patterns.
